### ISSUE TITLE
Split Out & Reword `CODE_OF_CONDUCT.md`

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/.github#5]
## Context

The current Code of Conduct is adapted from the [Contributor Covenant](https://www.contributor-covenant.org/), version 2.0. However, as the project and community has continued to grow and blossom, @catppuccin/staff and the @catppuccin/core team have found it increasingly difficult to enforce the code of conduct as it stands.

Unfortunately, we have had to recently ban someone from participating in the Discord community that was also a maintainer of one of the repositories in our GitHub organisation. Naturally, this raises some questions:

- **Are they still able to contribute by raising Issues / Pull Requests on GitHub?** (We currently don't check someone's background for current contributions)
- **If someone is barred from contributing to the GitHub organisation, should they be banned from joining and participating in the Discord community?**
- **What's required for someone to be allowed back into the Discord and/or allowed back as a maintainer?**

It is apparent that we need some sort of separation between GitHub & Discord as they are different communication platforms with entirely different purposes. We believe that it is unfeasible and outright impossible sometimes to "check" the background of GitHub contributors and maintainers to ensure that they are aligned with the current Code of Conduct.

As a result, we have decided to move away from the Contributor Covenant and split out the current document so that GitHub & Discord are not treated the same. 

## Acceptance Criteria

- [ ] Code of Conduct is reworded to move away from the Contributor Covenant and the language is **simplified** without sacrificing clarity.
- [ ] Split the Code of Conduct for GitHub & Discord respectively.

**Comment by sgoudham** [comment]
# Prior Art

- https://www.ruby-lang.org/en/conduct/

**Comment by isabelroses** [comment]
> If someone is barred from contributing to the GitHub organisation, should they be banned from joining and participating in the Discord community

In my opinion, if its come to the point where an individual has been banned from the discord, then it must be *bad* enough to mean that you don't want to interact with them or have them as identified with part of a community when they don't stand for the community or its values.

**Comment by sgoudham** [comment]
> In my opinion, if its come to the point where an individual has been banned from the discord, then it must be _bad_ enough to mean that you don't want to interact with them or have them as identified with part of a community when they don't stand for the community or its values.

When I wrote this, I was getting messages from the banned person and they were adamant for a second chance to be involved in the community again. 

My belief is that people _can_ change over time and should be given a second chance (of course, this is highly dependent on the severity of behaviour that led to the ban), but that trust is **immediately lost** even if they tip-toe the line during the second chance.

E.g. A maintainer having a sour/condescending attitudes towards community members. If it has been long enough and they haven't acted like that since the ban, that's when the second chance would kick in. Of course, this decision should also involve the community members affected by their behaviour.

**Comment by isabelroses** [comment]
> My belief is that people _can_ change over time and should be given a second chance (of course, this is highly dependent on the severity of behaviour that led to the ban), but that trust is **immediately lost** even if they tip-toe the line during the second chance.

I completely agree, but how would you determine, how long to leave it before you accept them back in, assuming they did/could change, assuming the nature of the violation was not so bad that its not worth it, and where would you draw that line. And how many "second chance" would they get, since its evitable that someone will get more then 1.

**Comment by ohitstom** [comment]
This may be meaningless coming from the banned individual in question, but i believe peoples social interactions can drastically be different to how they operate under the more professional environment on GitHub and when considering if a user should be banned both from the repo and the discord it would be important to consider how they've previously acted on GitHub and in case of a fear of said individual destroying the repo they have access too (not that it really matters since its git) put in place a 1 - 6 month temp ban based on how extreme their actions were / how untrustworthy they are.

Some people lack social maturity and whilst that wouldn't align with this orgs values I don't feel like that is fair to remove their creative outlet / passion for that side of the organization, but that's just the way I think about it the organizers may feel differently. 

Since currently you do not bar anyone banned on discord from interacting with organization repos they can still contribute and talk on issue and prs but they are just forced to wait a while for merging and collaboration on something they probably dont need help with considering they were previously its maintainer, this becomes less of an issue of removing a user from the org and more just making their life harder to keep something they are passionate maintained based on their inability to have a positive social interaction on discord.
